name: 'run_composer_script'
description: 'Configures styles'
inputs:
  script:
    type: string
    required: true
    description: 'script to run'
  path:
    type: string
    required: true
    description: 'Workdir for the script'
  run_composer_install:
    type: boolean
    required: false
    description: 'run composer install in the workdir'
    default: true
  install_options:
    type: string
    required: false
    description: 'Options to pass along to composer when running composer install'
    default: ''
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  output_artifact:
    type: string
    required: false
    description: 'Github run artifact for the output'
    default: 'run_composer_script'
  debug:
    type: string
    description: 'Appended to debugging scripts'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Run composer install
      if: ${{ inputs.run_composer_install == 'true' }}
      shell: bash
      run: |
        # run_composer_script: Run composer install
        ${{ inputs.debug }}
        echo -e "\033[0;35m### Running composer install with ${{ inputs.install_options }}\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          --workdir '/var/www/${{ inputs.path }}' \
          ${{ inputs.container_name }} \
          composer install ${{ inputs.install_options }}

    - name: Run composer script
      shell: bash
      run: |
        # run_composer_script: Run script ${{ inputs.script }}
        ${{ inputs.debug }}
        mkdir -p source/${{ inputs.path }}/.output source/${{ inputs.path }}/.coverage
        echo -e "\033[0;35m###  Run composer ${{ inputs.script }} in ${{ inputs.path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          --workdir '/var/www/${{ inputs.path }}' \
          ${{ inputs.container_name }} \
          composer ${{ inputs.script }}

    - name: Output php error log
      if: always()
      shell: bash
      run: |
        # styles: Output php error log
        ${{ inputs.debug }}
        if [ -s data/php/logs/error_log.txt ]; then
          echo -e "\033[0;35mPHP error log\033[0m"
          cat data/php/logs/error_log.txt
        fi

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output_artifact }}
        path: |
          source/${{ inputs.path }}/tests/output/*
          data/php/logs/error_log.txt
