name: 'composer_configure'
description: 'Configures oxidshop repositories'
inputs:
  organisation:
    type: string
    required: false
    description: 'Organisation for the repository'
    default: 'oxid-esales'
  repositories:
    type: string
    required: true
    description: 'Space separated list of repositories to configure'
  ref:
    type: string
    required: false
    description: 'Branch to check out for the enterprise repositories'
    default: ''
  options:
    type: string
    required: false
    description: 'Options to pass along to composer when requiring the repositories'
    default: '--no-update'
  update:
    type: boolean
    required: false
    description: 'Run composer update after configuring all repositories'
    default: true
  update_options:
    type: string
    required: false
    description: 'Options to pass along to composer when running composer update'
    default: '--no-interaction'
  dumpautoload:
    type: boolean
    required: false
    description: 'Run composer dumpautoload after installing all repos'
    default: false
  dumpautoload_options:
    type: string
    required: false
    description: 'Options to pass along to composer when running composer dumpautoload'
    default: '--dev'
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  enterprise_github_token:
    type: string
    required: false
    description: 'OAuth token to access enterprise repos'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Configure repositories
      shell: bash
      run: |
        # composer_configure: Configure repositories
        REPOSITORIES=$(echo -n "${{ inputs.repositories }}"| tr '\n' ' ')
        if [ -z "${{ inputs.ref }}" ]; then
          REFERENCE=""
        else
          REFERENCE=":${{ inputs.ref }}"
        fi
        ORGANIZATION=$(echo "${{ inputs.organisation }}" | tr '[:upper:]' '[:lower:]')
        if [ -n "${{ inputs.enterprise_github_token }}" ]; then
          echo -e "\033[0;35m###  configure github access ###\033[0m"
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            composer config github-protocols https
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            composer config -g github-oauth.github.com "${{ inputs.enterprise_github_token }}"
        fi

        for REPOSITORY in ${REPOSITORIES}; do
          ORG=$(echo "${REPOSITORY}"|sed -e 's|/.*||')
          if [[ -z "${ORG}" || "${ORG}" == "${REPOSITORY}" ]]; then
            ORG="${ORGANIZATION}"
          else
            REPOSITORY=$(echo "${REPOSITORY}"|sed -e 's|.*/||')
          fi
          REF=$(echo "${REPOSITORY}"|sed -e 's|.*:||')
          if [[ -z "${REF}" || "${REF}" == "${REPOSITORY}" ]]; then
            REF="${REFERENCE}"
          else
            REF=":${REF}"
            REPOSITORY=$(echo "${REPOSITORY}"|sed -e 's|:.*||')
          fi

          # compensate for repos with _ and config with -
          DASHED_REPO=$(echo "${REPOSITORY}"|tr '_', '-')
          echo -e "\033[0;35m###  configure ${ORG}/${DASHED_REPO} ###\033[0m"
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            composer config repositories.${ORG}/${DASHED_REPO} git "https://github.com/${{ inputs.organisation }}/${REPOSITORY}.git"
          echo -e "\033[0;35m###  require "${ORG}/${DASHED_REPO}${REF} with ${{ inputs.options }} ###\033[0m"
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            composer require "${ORG}/${DASHED_REPO}${REF}" ${{ inputs.options }}
        done
        if [ '${{ inputs.dumpautoload }}' == 'true' ]; then
          echo -e "\033[0;35m### Running composer dumpautoload with ${{ inputs.dumpautoload_options }}\033[0m"
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            composer dumpautoload ${{ inputs.dumpautoload_options }}
        fi
        if [ '${{ inputs.update }}' == 'true' ]; then
          echo -e "\033[0;35m### Running composer update with ${{ inputs.update_options }}\033[0m"
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            composer update ${{ inputs.update_options }}
        fi
