# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/actionlint"
      - "/append_report"
      - "/begin_report"
      - "/build_docker"
      - "/clean_cache"
      - "/composer_merge"
      - "/consolidate_artifacts"
      - "/generate_report"
      - "/load_cached_testplan"
      - "/prepare_shop"
      - "/run_custom_scripts"
      - "/run_test_script"
      - "/sonarcloud"
      - "/start_shop"
      - "/stop_shop"
      - "/yamllint"
    schedule:
      interval: "weekly"
      day: "monday"
    cooldown:
      semver-major-days: 7
    groups:
      major-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "major"
        group-by: dependency-name
