name: 'install_themes'
description: 'Installs oxidshop themes'
inputs:
  themes:
    type: string
    description: 'Space separated list of themes to install'
    required: true
  options:
    type: string
    description: 'Options to pass along to composer during install'
    required: false
    default: '--with-all-dependencies'
  update:
    type: boolean
    description: ' Run composer update after installing all themes'
    required: false
    default: true
  update_options:
    type: string
    description: 'Options to pass along to composer during install'
    required: false
    default: '--no-interaction'
  container:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
    
runs:
  using: "composite"
  steps:
  - name: Install themes
    shell: bash
    run: |
      for THEME in ${{ inputs.themes }}; do
        echo -e "\033[0;35m### Installing ${THEME} with ${{ inputs.options }}\033[0m"
        docker-compose exec -T ${{ inputs.container_options }} \
          ${{ inputs.container }} \
          composer require "${THEME}" ${{ inputs.options }}
      done
      if [ '${{ inputs.update }}' == 'true' ]; then
        echo -e "\033[0;35m### Running composer update with ${{ inputs.update_options }}\033[0m"
        docker-compose exec -T ${{ inputs.container_options }} \
          ${{ inputs.container }} \
          composer update ${{ inputs.update_options }}
      fi
