name: 'install_themes'
description: 'Installs oxidshop themes'
inputs:
  themes:
    type: string
    description: 'Space separated list of themes to install'
    required: true
  options:
    type: string
    description: 'Options to pass along to composer'
    required: false
    default: '--with-all-dependencies'
  update:
    type: boolean
    description: ' Run composer update after installing all themes'
    required: false
    default: true
    
runs:
  using: "composite"
  steps:
  - name: Install themes
    shell: bash
    run: |
      for THEME in ${{ inputs.themes }}; do
        docker-compose exec -T php composer require "${THEME}" ${{ inputs.options }}
      done
      if [ '${{ inputs.update }}' == 'true' ]; then
        docker-compose exec -T php composer update --no-interaction
      fi
