name: 'install_themes'
description: 'Installs oxidshop themes'
inputs:
  themes:
    type: string
    required: true
    description: 'Space separated list of themes to install'
  options:
    type: string
    required: false
    description: 'Options to pass along to composer during install'
    default: '--with-all-dependencies'
  update:
    type: boolean
    required: false
    description: 'Run composer update after installing all themes'
    default: true
  update_options:
    type: string
    required: false
    description: 'Options to pass along to composer when running composer update'
    default: '--no-interaction'
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'

runs:
  using: "composite"
  steps:
    - name: Install themes
      shell: bash
      run: |
        for THEME in ${{ inputs.themes }}; do
          echo -e "\033[0;35m### Installing ${THEME} with ${{ inputs.options }}\033[0m"
          docker-compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \
            ${{ inputs.container }} \
            composer require "${THEME}" ${{ inputs.options }}
        done
        if [ '${{ inputs.update }}' == 'true' ]; then
          echo -e "\033[0;35m### Running composer update with ${{ inputs.update_options }}\033[0m"
          docker-compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \
            ${{ inputs.container }} \
            composer update ${{ inputs.update_options }}
        fi

    - name: Generate deprecation warning to summary page
      shell: bash
      run: |
        cat <<EOF
        echo "Deprecation Warning:" >> $GITHUB_STEP_SUMMARY
        echo "---------------------" >> $GITHUB_STEP_SUMMARY
        echo -e "\033[0;31m### This install_theme actions are deprecated and may not be supported  \033[0m" >> $GITHUB_STEP_SUMMARY
        exit 1
        EOF

    - name: 'Output report'
      shell: bash
      run: |
        cat >> slack_deprecated.json >>EOF
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "emoji": true,
                  "text": "deprecation warning install_themes"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "the workflow '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' is using deprecated install_themes action. The action install_themes has been replaced by the respective composer_require action."
                }
              }
            ]
          }
        EOF

    - name: Send a deprecation warning link to slack channel
      uses: slackapi/slack-github-action@v1
      with:
        payload-file-path: 'slack_deprecated.json'
      env:
        SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
