name: 'install_themes'
description: 'Installs oxidshop themes'
inputs:
  themes:
    description: 'Space separated list of themes to install'
    required: true
  options:
    description: 'Options to pass along to composer'
    required: false
    default: '--with-all-dependencies'
    
runs:
  using: "composite"
  steps:
  - name: Install APEX theme
        run: |
          for THEME in ${{ inputs.themes }}
          docker-compose exec -T php composer require "${THEME}" ${{ inputs.options }}