name: 'shop_setup_tests'
description: 'Executes shop setup tests'
inputs:
  prepared_shop:
    type: string
    description: 'Name of the cached object from prepare_shop'
    required: true
  php:
    type: string
    required: true
    description: 'Version of PHP for this instance'
  mysql:
    type: string
    required: true
    description: 'Version of MySQL for this instance'
  is_enterprise:
    type: boolean
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Initialize
      shell: bash
      run: |
        if [ "${{ inputs.is_enterprise}}" == "true" ]; then
          cat >> $GITHUB_ENV <<EOF
        EXEC_PHP=docker-compose exec -T php
        TEST_YAML=vendor/oxid-esales/oxideshop-ee/Tests/codeception.yml
        PHPUNIT_LOGFILE=codeception_PHP${{ inputs.php }}_MYSQL${{ inputs.mysql }}_phpunit_log.txt
        CODECEPTION_OUTPUT_PATH=source/vendor/oxid-esales/oxideshop-ee/Tests/Codeception/_output
        EOF
        else
          cat >> $GITHUB_ENV <<EOF
        EXEC_PHP=docker-compose exec -T php
        TEST_YAML=tests/codeception.yml
        PHPUNIT_LOGFILE=shop_setup_PHP${{ inputs.php }}_MYSQL${{ inputs.mysql }}_phpunit_log.txt
        CODECEPTION_OUTPUT_PATH=source/tests/Codeception/_output
        EOF
        fi
        cat $GITHUB_ENV

    - name: Install APEX theme
      if: ${{ inputs.is_enterprise == 'false' }}
      shell: bash
      run: |
        docker-compose exec -T php composer require oxid-esales/apex-theme --with-all-dependencies

    - name: Install admin theme
      if: ${{ inputs.is_enterprise == 'false' }}
      shell: bash
      run: |
        docker-compose exec -T php composer require oxid-esales/twig-admin-theme


    - name: Build Codeception (ee)
      if: ${{ inputs.is_enterprise == 'true' }}
      shell: bash
      run: |
        $EXEC_PHP php vendor/bin/codecept build \
        -c vendor/oxid-esales/oxideshop-ee/Tests/codeception.yml

    - name: Run Codeception tests (ee)
      if: ${{ inputs.is_enterprise == 'true' }}
      shell: bash
      # why do we use run in ee and exec in ce?
      run: |
        docker-compose run -T \
          -e SELENIUM_SERVER_HOST=selenium \
          -e BROWSER_NAME=chrome \
          -e DB_NAME=setup_test \
          -e DB_USERNAME=root \
          -e DB_PASSWORD=root \
          -e DB_HOST=mysql \
          -e DB_PORT=3306 \
          -e SHOP_URL=http://localhost.local/ \
          -e SHOP_SOURCE_PATH=/var/www/source/ \
          php \
            php vendor/bin/codecept run acceptanceSetup \
          -c $TEST_YAML \
        --ext DotReporter \
        | tee $PHPUNIT_LOGFILE 2>&1 || true
        if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error|DID NOT FINISH' $PHPUNIT_LOGFILE; then exit 1; fi

    - name: Run Codeception tests (ce)
      if: ${{ inputs.is_enterprise == 'false' }}
      shell: bash
      run: |
        docker-compose exec -T \
          -e SELENIUM_SERVER_HOST=selenium \
          -e BROWSER_NAME=chrome \
          -e DB_NAME=setup_test \
          -e DB_USERNAME=root \
          -e DB_PASSWORD=root \
          -e DB_HOST=mysql \
          -e DB_PORT=3306 \
          -e SHOP_URL=http://localhost.local/ \
          -e SHOP_SOURCE_PATH=/var/www/source/ \
          php vendor/bin/codecept run acceptanceSetup \
            -c $TEST_YAML \
            --ext DotReporter \
            --skip-group flow_theme \
            | tee $PHPUNIT_LOGFILE 2>&1 || true
        if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error|DID NOT FINISH' $PHPUNIT_LOGFILE; then
          exit 1
        fi

    - name: Upload PHPUnit Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-logs
        path: ${{ env.PHPUNIT_LOGFILE }}
        if-no-files-found: error
        retention-days: 7

    - name: Upload Codeception Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: shop_setup-artifacts-PHP${{ inputs.php }}-MYSQL${{ inputs.mysql }}
        path: ${{ env.CODECEPTION_OUTPUT_PATH }}/*
        if-no-files-found: ignore
        retention-days: 7