name: 'phpstan'
description: 'Run phpstan'
inputs:
  title:
    type: string
    required: false
    default: 'shop'
    description: 'Name of the report without the suffix'
  source_path:
    type: string
    required: false
    default: 'source'
    description: 'Folder to run phpstan in'
  report_path:
    type: string
    required: false
    default: 'reports'
    description: 'Folder to save the report to'
  neon_file:
    type: string
    required: false
    default: 'tests/PhpStan/phpstan.neon'
    description: 'Folder to save the report to'
  verbose:
    type: boolean
    required: false
    default: false
    description: 'Show the report in the job console too'
  generate_baseline:
    type: boolean
    required: false
    default: false
    description: 'Generate a baseline file'
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  output_artifact:
    type: string
    required: false
    description: 'Github run artifact for the styles output'
    default: 'phpmd'
  failure_pattern:
    "errors":[1-9][0-9]*
    "file_errors":[1-9][0-9]*
  debug:
    type: string
    description: 'Appended to debugging scripts'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Run PHP Mess Detector
      continue-on-error: true
      shell: bash
      run: |
        # phpstan: Run PHPStan
        ${{ inputs.debug }}
        mkdir -p "source/${{inputs.report_path}}"
        echo -e "\033[0;35m###  Generate phpstan-report in ${{ inputs.source_path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          ${{ inputs.container_name }} \
          /var/www/vendor/bin/phpstan \
          -c/var/www/${{inputs.neon_file}} analyse /var/www/${{ inputs.source_path }} \
          --no-progress \
          --error-format=json \
        | cat >source/${{inputs.report_path }}/phpstan-${{ inputs.title }}.json || true

        if [ '${{ inputs.generate_baseline }}' == 'true' ]; then
          echo -e "\033[0;35m###  Generate phpstan baseline for ${{ inputs.source_path }} ###\033[0m"
          docker compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name }} \
            /var/www/vendor/bin/phpstan \
            -c/var/www/${{inputs.neon_file}} analyse /var/www/${{ inputs.source_path }} \
            --generate-baseline /var/www/${{inputs.report_path }}/phpstan-${{ inputs.title }}-baseline.neon \
            --no-progress --quiet \
          || true
        fi

        if [ '${{inputs.verbose}}' == 'true' ]; then
          echo -e "\033[0;35m###  Run phpstan in ${{ inputs.source_path }} ###\033[0m"
          docker compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name }} \
            /var/www/vendor/bin/phpstan \
            -c/var/www/${{inputs.neon_file}} analyse /var/www/${{ inputs.source_path }} 
            --no-progress \
          | tee -a source/${{inputs.report_path}}/phpstan-${{ inputs.title }}.txt || true
        fi

        if [ -s data/php/logs/error_log.txt ]; then
          echo -e "\033[0;35mPHP error log\033[0m"
          cat data/php/logs/error_log.txt | tee -a ${{inputs.report_path}}/php_error_log-${{ inputs.title }}.txt
        fi

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output_artifact }}
        path: |
          source/${{ inputs.report_path }}*

    - name: Check results
      shell: bash
      run: |
        # phpmd: Check results
        ${{ inputs.debug }}
        FILE='source/${{inputs.report_path }}/phpstan-${{ inputs.title }}.json'
        PURPLE=$(echo -e "\033[0;31m")
        NOCOLOR=$(echo -e "\033[0m")
        if [ ! -s "${FILE}" ]; then
          cat <<EOF
        ${PURPLE}###############################################################################
        ### JSON Report is empty! Seems like no tests have been run!
        ###############################################################################${NOCOLOR}
        EOF
          exit 1
        fi
        cat >failure_pattern.tmp <<EOF
        ${{ inputs.failure_pattern}}
        EOF
        sed -e 's|(.*)\r|$1|' -i failure_pattern.tmp
        while read -r LINE ; do
          if [ -n "${LINE}" ]; then
            if grep -q -E "${LINE}" "${FILE}"; then
              echo -e "\033[0;31m phpstan failed matching pattern ${LINE}"
              grep -E "${LINE}" "${FILE}"
              exit 1
            else
                echo -e "\033[0;32m phpstan passed matching pattern ${LINE}"
            fi
          fi
        done <failure_pattern.tmp
