name: 'phpstan'
description: 'Run phpstan'
inputs:
  title:
    type: string
    required: false
    default: 'shop'
    description: 'Name of the report without the suffix'
  source_path:
    type: string
    required: false
    default: 'source'
    description: 'Folder to run phpstan in'
  report_path:
    type: string
    required: false
    default: 'reports'
    description: 'Folder to save the report to'
  neon_file:
    type: string
    required: false
    default: 'tests/PhpStan/phpstan.neon'
    description: 'Folder to save the report to'
  verbose:
    type: boolean
    required: false
    default: false
    description: 'Show the report in the job console too'
  generate_baseline:
    type: boolean
    required: false
    default: false
    description: 'Generate a baseline file'
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  output_artifact:
    type: string
    required: false
    description: 'Github run artifact for the styles output'
    default: 'phpmd'
  debug:
    type: string
    description: 'Appended to debugging scripts'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Run PHP Mess Detector
      continue-on-error: true
      shell: bash
      run: |
        # phpstan: Run PHPStan
        ${{ inputs.debug }}
        mkdir -p "source/${{inputs.report_path}}"
        BASELINE_OPTIONS=''
        if [ '${{ inputs.generate_baseline }}' == 'true' ]; then
          BASELINE_OPTIONS='--generate-baseline /var/www/${{inputs.report_path }}/phpstan-${{ inputs.title }}-baseline.neon'
        fi
        echo -e "\033[0;35m###  Generate phpstan-report in ${{ inputs.source_path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          ${{ inputs.container_name }} \
          /var/www/vendor/bin/phpstan \
          -c/var/www/${{inputs.neon_file}} analyse /var/www/${{ inputs.source_path }} \
          ${BASELINE_OPTIONS} \
          --error-format=json \
        | cat >/source/${{inputs.report_path }}/phpstan-${{ inputs.title }}.json || true

        if [ '${{inputs.verbose}}' == 'true' ]; then
          echo -e "\033[0;35m###  Run phpstan in ${{ inputs.source_path }} ###\033[0m"
          docker compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name }} \
            /var/www/vendor/bin/phpstan \
            -c/var/www/${{inputs.neon_file}} analyse /var/www/${{ inputs.source_path }} 
            --no-progress \
          | tee -a source/${{inputs.report_path}}/phpstan-${{ inputs.title }}.txt || true
        fi

        if [ -s data/php/logs/error_log.txt ]; then
          echo -e "\033[0;35mPHP error log\033[0m"
          cat data/php/logs/error_log.txt | tee -a ${{inputs.report_path}}/php_error_log-${{ inputs.title }}.txt
        fi

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output_artifact }}
        path: |
          source/${{ inputs.report_path }}*
