name: 'run_test_script'
description: 'Configures styles'
inputs:
  script:
    type: string
    required: true
    description: 'script to run'
  path:
    type: string
    required: true
    description: 'Workdir for the script'
  workdir:
    type: string
    required: false
    description: 'Workdir for the script'
    default: ''
  run_composer_install:
    type: boolean
    required: false
    description: 'run composer install in the workdir'
    default: true
  install_options:
    type: string
    required: false
    description: 'Options to pass along to composer when running composer install'
    default: ''
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  output_artifact:
    type: string
    required: false
    description: 'Github run artifact for the output'
    default: 'run_test_script'
  debug:
    type: string
    description: 'Appended to debugging scripts'
    default: ''
    required: false
  github_token:
    type: string
    description: 'Github token for composer'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Run composer script
      if: ${{ ! startsWith(inputs.script, '~/') }}
      shell: bash
      run: |
        # run_test_script: Run composer script ${{ inputs.script }}
        ${{ inputs.debug }}
        TESTDIR='tests'
        if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
          TESTDIR='Tests'
          if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
            echo -e "\033[0;31m###  Could not find folder tests or Tests in ${{ inputs.path }}, creating it ###\033[0m"
            TESTDIR='tests'
            mkdir -p "source/${{ inputs.path }}/${TESTDIR}"
          fi
        fi
        mkdir -p source/${{ inputs.path }}/${TESTDIR}/Output source/${{ inputs.path }}/${TESTDIR}/Reports
        echo -e "\033[0;35m###  Run composer ${{ inputs.script }} in ${{ inputs.path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          -e GITHUB_TOKEN=${{ inputs.github_token }} \
          ${{ inputs.container_options }} \
          -e ABSOLUTE_PATH=${{ inputs.path }} \
          --workdir '/var/www/${{ inputs.workdir }}' \
          ${{ inputs.container_name }} \
          composer ${{ inputs.script }}

    - name: Run shell script
      if: ${{ startsWith(inputs.script, '~/' ) }}
      shell: bash
      run: |
        # run_test_script: Run shell script ${{ inputs.script }}
        ${{ inputs.debug }}
        TESTDIR='tests'
        if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
          TESTDIR='Tests'
          if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
            echo -e "\033[0;31m###  Could not find folder tests or Tests in ${{ inputs.path }} ###\033[0m"
            exit 1
          fi
        fi
        mkdir -p "source/${{ inputs.path }}/${TESTDIR}/Output" "source/${{ inputs.path }}/${TESTDIR}/Reports"
        SCRIPT=$(echo '${{ inputs.script }}'|sed -e "s|^~/|${TESTDIR}/Scripts/|")
        if [ ! -f "source/${{ inputs.path }}/${SCRIPT}" ]; then
          SCRIPT=$(echo '${{ inputs.script }}'|sed -e "s|^~/|${TESTDIR}/scripts/|")
        fi
        S=$(echo "${SCRIPT}"|sed -e 's|\s.*||')
        if [ ! -f "source/${{ inputs.path }}/${S}" ]; then
          echo -e "\033[0;31m###  Could not find source/${{ inputs.path }}/${S} ###\033[0m"
        fi
        chmod a+x "source/${{ inputs.path }}/${S}"
        echo -e "\033[0;35m###  Run ${SCRIPT} in ${{ inputs.path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          -e GITHUB_TOKEN=${{ inputs.github_token }} \
          ${{ inputs.container_options }} \
          -e ABSOLUTE_PATH=${{ inputs.path }} \
          --workdir '/var/www/${{ inputs.workdir }}' \
          ${{ inputs.container_name }} \
          /var/www/${{ inputs.path }}/${SCRIPT}

    - name: Output php error log
      if: always()
      shell: bash
      run: |
        # run_test_script: Output php error log
        ${{ inputs.debug }}
        TESTDIR='tests'
        if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
          TESTDIR='Tests'
          if [ ! -d "source/${{ inputs.path }}/${TESTDIR}" ]; then
            echo -e "\033[0;31m###  Could not find folder tests or Tests in ${{ inputs.path }}, creating it ###\033[0m"
            TESTDIR='tests'
          fi
        fi
        if [ -s data/php/logs/error_log.txt ]; then
          echo -e "\033[0;35mPHP error log\033[0m"
          cat data/php/logs/error_log.txt
        fi
        touch data/php/logs/error_log.txt
        mkdir -p "source/${{ inputs.path }}/${TESTDIR}/Output"
        cp source/composer.json source/${{ inputs.path }}/${TESTDIR}/Output/
        cp source/composer.lock source/${{ inputs.path }}/${TESTDIR}/Output/
        cp data/php/logs/error_log.txt source/${{ inputs.path }}/${TESTDIR}/Output/
        cp data/mysql/mysql/slow_log* source/${{ inputs.path }}/${TESTDIR}/Output/
        cp data/mysql/mysql/general_log* source/${{ inputs.path }}/${TESTDIR}/Output/
        if [ -f source/source/log/oxideshop.log ]; then
          mkdir -p source/${{ inputs.path }}/${TESTDIR}/Output/source/log
          cp source/source/log/oxideshop.log source/${{ inputs.path }}/${TESTDIR}/Output/source/log/
        fi
        if [ -f source/vendor/oxid-esales/oxideshop-ce/log/oxideshop.log ]; then
          mkdir -p source/${{ inputs.path }}/${TESTDIR}/Output/source/vendor/oxid-esales/oxideshop-ce/log
          cp source/vendor/oxid-esales/oxideshop-ce/log/oxideshop.log source/${{ inputs.path }}/${TESTDIR}/Output/source/vendor/oxid-esales/oxideshop-ce/log/
        fi
        docker compose logs --tail=all >source/${{ inputs.path }}/${TESTDIR}/Output/docker-compose.log
        for c in $(docker ps -aq); do
          echo -e "\033[0;35m###  Logs for $c ###\033[0m"
          docker logs -n 2000 $c >source/${{ inputs.path }}/${TESTDIR}/Output/docker-$c.log
        done

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output_artifact }}
        path: |
          source/${{ inputs.path }}/tests/Output/*
