name: 'login into dockerhub and build docker images'
description: 'build and push docker images'
inputs:
  dockerhub_username:
    type: string
    required: true
    description: 'username to login into dockerhub'
  dockerhub_password:
    type: string
    required: true
    description: 'password to login into dockerhub'
  image_name:
    type: string
    required: true
    description: 'name of the image'
  tags:
    type: string
    required: false
    description: 'version of the image'
  build-args:
    type: string
    required: false
    description: 'matrix versions and dependencies'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log into Docker Hub
      if: ${{ github.event_name != 'pull_request' && inputs.dockerhub_username != '' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.image_name }}
        file: ${{ inputs.image_name }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' && inputs.dockerhub_username != '' }}
        tags: ${{ inputs.tags }}
        build-args: ${{ inputs.build_args }}
