name: 'unit_tests'
description: 'Executes unit tests in a running shop'
inputs:
  php:
    type: string
    required: false
    description: 'Version of PHP for this instance'
    default: ${{ matrix.php }}
  mysql:
    type: string
    required: false
    description: 'Version of MySQL for this instance'
    default: ${{ matrix.mysql }}
  is_enterprise:
    type: boolean
    required: false
    description: 'This action can be used on the community edition (ce) and enterprise edition (ee) of the shop. On top of setting this to true, a few extra variables/secrets must be provided for using the action on ee.'
    default: false
runs:
  using: "composite"
  steps:
    - name: Add environment variables (ee)
      if: ${{ inputs.is_enterprise == 'true' }}
      shell: bash
      run: |
        cat >> $GITHUB_ENV <<EOF
        EXEC_PHP=docker-compose exec -T php
        UNIT_FOLDER=vendor/oxid-esales/oxideshop-ee/Tests/Unit
        PHPUNIT_LOGFILE=unit_PHP${{ inputs.php }}_MYSQL${{ inputs.mysql }}_phpunit_log.txt
        EOF
        cat $GITHUB_ENV

    - name: Add environment variables (ce)
      if: ${{ inputs.is_enterprise == 'false' }}
      shell: bash
      run: |
        cat >> $GITHUB_ENV <<EOF
        EXEC_PHP=docker-compose exec -T php
        UNIT_FOLDER=tests/Unit
        PHPUNIT_LOGFILE=unit_PHP${{ inputs.php }}_MYSQL${{ inputs.mysql }}_phpunit_log.txt
        EOF
        cat $GITHUB_ENV

    # warum haben wir in ee "php vendor/bin/phpunit" und in ce nur "vendor/bin/phpunit"
    - name: Run PHPUnit Unit tests
      shell: bash
      run: |
        $EXEC_PHP php vendor/bin/phpunit -c phpunit.xml $UNIT_FOLDER | tee $PHPUNIT_LOGFILE 2>&1 || true
        if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' $PHPUNIT_LOGFILE; then
          exit 1
        fi

    - name: Upload PHPUnit Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-logs
        path: ${{ env.PHPUNIT_LOGFILE }}
        if-no-files-found: error
        retention-days: 7
