name: 'begin_report'
description: 'Creates the initial markdown headers for the reports'
inputs:
  repository:
    type: string
    required: true
    description: 'URL of the github repository'
  job:
    type: string
    required: false
    description: 'URL of the job'
    default: '-'
  testplan:
    type: string
    required: false
    description: 'URL/file name of the test plan'
    default: '-'
  title:
    type: string
    required: false
    description: 'Title of the job'
    default: 'default'

runs:
  using: "composite"
  steps:
    - name: 'Write Report header'
      shell: bash
      run: |
        # begin_report: Write Report header
        mkdir -p reports job_status slack_reports
        cat >reports/000-header.md <<EOF
        # ${{inputs.title}}
        EOF
        cat >slack_reports/000-header.md <<EOF
        Repository: ${{ inputs.repository }}
        Job: ${{ inputs.job }}
        Testplan: ${{ inputs.TESTPLAN }}

        EOF

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testplan
        path: |
          reports/000-header.md.md
          slack_reports/000-header.md
        if-no-files-found: ignore
        retention-days: 7
