name: 'runtests'
description: 'Executes vendor/bin/runtests in a running container and uploads the logs as artefacts'
inputs:
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  reset_shop:
    type: boolean
    required: false
    description: 'Should we run vendor/bin/reset-shop before the test'
    default: true
  test:
    type: string
    required: false
    description: 'Name of the test or folder to run'
    default: 'AllTestsUnit'
  additional_options:
    type: string
    required: false
    description: 'Optional: Additional options to pass to phpunit'
    default: ''
  logfile:
    type: string
    required: false
    description: 'Name of the output logfile'
    default: 'deprecated_tests_log.txt'
  logfile_artifact:
    type: string
    required: false
    description: 'Github run artifact to put the logfile in'
    default: 'phpunit-logs'
  output_files:
    type: string
    required: false
    description: 'phpunit output and test settings'
    default: |
      source/unit.cov
      source/source/log/oxideshop.log
      data/php/logs/error_log.txt
  output_artifact:
    type: string
    required: false
    description: 'Github run artifact for the phpunit output'
    default: 'phpunit-artifacts'
  coverage_path:
    type: string
    required: false
    description: 'Path for the coverage file, not uploaded if it is empty'
    default: ''
  coverage_artifact:
    type: string
    required: false
    description: 'Github run artifact for the coverage file'
    default: 'coverage-reports'
  failure_pattern:
    type: string
    required: false
    description: 'Grep pattern which indicate that the test failed'
    default: 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error|DID NOT FINISH'
runs:
  using: "composite"
  steps:
    - name: Reset shop
      if: ${{ inputs.reset_shop == 'true' }}
      shell: bash
      run: |
        docker-compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \
          ${{ inputs.container_name}} \
          php vendor/bin/reset-shop

    - name: Run PHPUnit Unit tests
      shell: bash
      run: |
        docker-compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \
          ${{ inputs.container_name}} \
          php vendor/bin/runtests \
            ${{ inputs.additional_options }} \
            "${{ inputs.test }}" \
          | tee "${{ inputs.logfile }}" 2>&1 || true

    - name: Upload Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.logfile_artifact }}
        path: ${{ inputs.logfile }}
        if-no-files-found: error
        retention-days: 7

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.output_artifact }}
        path: ${{ inputs.output_files }}
        if-no-files-found: ignore
        retention-days: 7

    - name: Upload Coverage Report
      if: ${{  always() && inputs.coverage_path != '' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.coverage_artifact }}
        path: ${{ inputs.coverage_path }}
        if-no-files-found: ignore
        retention-days: 7


    - name: Check results
      shell: bash
      run: |
        PURPLE=$(echo -e "\033[0;31m")
        NOCOLOR=$(echo -e "\033[0m")
        if [ ! -s "${{ inputs.logfile }}" ]; then
          cat <<EOF
        ${PURPLE}###############################################################################
        ### Log file is empty! Seems like no tests have been run!
        ###############################################################################${NOCOLOR}
        EOF
          exit 1
        fi
        if grep -q -Ei '${{ inputs.failure_pattern}}' "${{ inputs.logfile }}"; then
          cat <<EOF
        ${PURPLE}###############################################################################
        ### phpunit test ${{ inputs.test }} failed
        ###############################################################################${NOCOLOR}
        EOF
          grep -Ei '${{ inputs.failure_pattern}}' "${{ inputs.logfile }}"
          exit 1
        fi
        if [[ -n "${{ inputs.coverage_path }}" && ! -s "${{ inputs.coverage_path }}" ]]; then
          cat <<EOF
        ${PURPLE}###############################################################################
        ### "${{ inputs.coverage_path }}" is empty!
        ###############################################################################${NOCOLOR}
        EOF
          exit 1
        fi
