name: 'integration_tests'
description: 'Executes integration tests in a running shop'
inputs:
  php:
    type: string
    required: true
    description: 'Version of PHP for this instance'
  mysql:
    type: string
    required: true
    description: 'Version of MySQL for this instance'
  is_enterprise:
    type: boolean
    required: false
    default: true
outputs:
runs:
  using: "composite"
  steps:
    - name: Add environment variables
      if: is_enterprise == true
      run: |
        EXEC_PHP="docker-compose exec -T php"
        echo "EXEC_PHP=$EXEC_PHP" >> $GITHUB_ENV
        UNIT_FOLDER="vendor/oxid-esales/oxideshop-ee/Tests/Integration"
        echo "UNIT_FOLDER=$UNIT_FOLDER" >> $GITHUB_ENV
        PHPUNIT_LOGFILE="integration_PHP${{ input.php }}_MYSQL${{ input.mysql }}_phpunit_log.txt"
        echo "PHPUNIT_LOGFILE=$PHPUNIT_LOGFILE" >> $GITHUB_ENV

    - name: Add environment variables
      if: is_enterprise == false
      run: |
        EXEC_PHP="docker-compose exec -T php"
        echo "EXEC_PHP=$EXEC_PHP" >> $GITHUB_ENV
        UNIT_FOLDER="tests/Integration"
        echo "UNIT_FOLDER=$UNIT_FOLDER" >> $GITHUB_ENV
        PHPUNIT_LOGFILE="integration_PHP${{ input.php }}_MYSQL${{ input.mysql }}_phpunit_log.txt"
        echo "PHPUNIT_LOGFILE=$PHPUNIT_LOGFILE" >> $GITHUB_ENV

    # warum haben wir in ee "php vendor/bin/phpunit" und in ce nur "vendor/bin/phpunit"
    - name: Run PHPUnit Unit tests
      run: |
        $EXEC_PHP php vendor/bin/phpunit -c phpunit.xml --bootstrap tests/bootstrap.php $UNIT_FOLDER | tee $PHPUNIT_LOGFILE 2>&1 || true
        if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' $PHPUNIT_LOGFILE; then exit 1; fi

    - name: Upload PHPUnit Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-logs
        path: ${{ env.PHPUNIT_LOGFILE }}
        if-no-files-found: error
        retention-days: 7
