name: 'integration_tests'
description: 'Executes integration tests in a running shop'
inputs:
  php:
    type: string
    required: true
    description: 'Version of PHP for this instance'
  mysql:
    type: string
    required: true
    description: 'Version of MySQL for this instance'
  is_enterprise:
    type: boolean
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Add environment variables (ee)
      if: ${{ inputs.is_enterprise == 'true' }}
      shell: bash
      run: |
        cat >> $GITHUB_ENV <<EOF
        EXEC_PHP=docker-compose exec -T php
        UNIT_FOLDER=vendor/oxid-esales/oxideshop-ee/Tests/Integration
        PHPUNIT_LOGFILE=integration_PHP${{ inputs.php }}_MYSQL${{ inputs.mysql }}_phpunit_log.txt
        EOF
        cat $GITHUB_ENV

    - name: Add environment variables (ce)
      if: ${{ inputs.is_enterprise == 'false' }}
      shell: bash
      run: |
        cat >> $GITHUB_ENV <<EOF
        EXEC_PHP=docker-compose exec -T php
        UNIT_FOLDER=tests/Integration
        PHPUNIT_LOGFILE=integration_PHP${{ inputs.php }}_MYSQL${{ inputs.mysql }}_phpunit_log.txt
        EOF
        cat $GITHUB_ENV

    # warum haben wir in ee "php vendor/bin/phpunit" und in ce nur "vendor/bin/phpunit"
    - name: Run PHPUnit Unit tests
      shell: bash
      run: |
        $EXEC_PHP php vendor/bin/phpunit -c phpunit.xml --bootstrap tests/bootstrap.php $UNIT_FOLDER | tee $PHPUNIT_LOGFILE 2>&1 || true
        if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' $PHPUNIT_LOGFILE; then exit 1; fi

    - name: Upload PHPUnit Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-logs
        path: ${{ env.PHPUNIT_LOGFILE }}
        if-no-files-found: error
        retention-days: 7
