name: 'phpmd'
description: 'Run phpmd'
inputs:
  title:
    type: string
    required: false
    default: 'shop'
    description: 'Name of the report without the suffix'
  source_path:
    type: string
    required: false
    default: 'source'
    description: 'Folder to run phpmd in'
  report_path:
    type: string
    required: false
    default: 'reports'
    description: 'Folder to save the report to'
  config:
    type: string
    required: false
    default: 'tests/PhpMd/standard.xml'
    description: 'Folder to save the report to'
  verbose:
    type: boolean
    required: false
    default: false
    description: 'Show the PHPMD report in the job console too'
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  output_artifact:
    type: string
    required: false
    description: 'Github run artifact for the styles output'
    default: 'phpmd'
  debug:
    type: string
    description: 'Appended to debugging scripts'
    default: ''
    required: false
  failure_pattern:
    type: string
    required: false
    description: 'Grep pattern which indicate that the test failed'
    default: |
      "warnings":
      "violations":
      "errors":
runs:
  using: "composite"
  steps:
    - name: Run PHP Mess Detector
      continue-on-error: true
      shell: bash
      run: |
        # phpmd: Run PHP Mess Detector
        ${{ inputs.debug }}
        mkdir -p "source/${{inputs.report_path}}"

        echo -e "\033[0;35m###  Generate phpmd-report in ${{ inputs.source_path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          ${{ inputs.container_name }} \
          /var/www/vendor/bin/phpmd /var/www/${{ inputs.source_path }} json \
          /var/www/${{ inputs.config }} \
          --ignore-errors-on-exit --ignore-violations-on-exit \
          --reportfile '/var/www/${{inputs.report_path }}/phpmd-${{ inputs.title }}.json' || true

        if [ '${{inputs.verbose}}' == 'true' ]; then
          echo -e "\033[0;35m###  Run phpmd in ${{ inputs.source_path }} ###\033[0m"
          docker compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name }} \
            /var/www/vendor/bin/phpmd /var/www/${{ inputs.source_path }} ansi \
            /var/www/${{ inputs.config }} \
            --ignore-errors-on-exit --ignore-violations-on-exit \
          | tee -a source/${{inputs.report_path}}/phpmd-${{ inputs.title }}.txt || true
        fi

        if [ -s data/php/logs/error_log.txt ]; then
          echo -e "\033[0;35mPHP error log\033[0m"
          cat data/php/logs/error_log.txt | tee -a ${{inputs.report_path}}/php_error_log-${{ inputs.title }}.txt
        fi

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output_artifact }}
        path: |
          source/${{ inputs.report_path }}*

    - name: Check results
      shell: bash
      run: |
        # phpmd: Check results
        ${{ inputs.debug }}
        FILE='source/${{inputs.report_path }}/phpmd-${{ inputs.title }}.json'
        PURPLE=$(echo -e "\033[0;31m")
        NOCOLOR=$(echo -e "\033[0m")
        if [ ! -s "${FILE}" ]; then
          cat <<EOF
        ${PURPLE}###############################################################################
        ### JSON Report is empty! Seems like no tests have been run!
        ###############################################################################${NOCOLOR}
        EOF
          exit 1
        fi
        cat >failure_pattern.tmp <<EOF
        ${{ inputs.failure_pattern}}
        EOF
        sed -e 's|(.*)\r|$1|' -i failure_pattern.tmp
        while read -r LINE ; do
          if [ -n "${LINE}" ]; then
            if grep -q -E "${LINE}" "${FILE}"; then
              echo -e "\033[0;31m phpmd failed matching pattern ${LINE}"
              grep -E "${LINE}" "${FILE}"
              exit 1
            else
                echo -e "\033[0;32m runtest passed matching pattern ${LINE}"
            fi
          fi
        done <failure_pattern.tmp
