name: 'cleanup_workspace'
description: 'Deletes files and cleans up the docker environment'
runs:
  using: "composite"
  steps:
    - name: Cleanup workspace
      shell: bash
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./

    - name: Kill docker containers
      if: env.ACT == false
      shell: bash
      run: |
        docker ps -a
        for c in $(docker ps -q); do
          echo "Killing container $c"
          docker kill $c
        done

    - name: Cleanup Docker
      shell: bash
      run: docker system prune --force
