workflow:
  matrix: &matrix
    php: '["8.0","8.1"]'
    mysql: '["mysql-5.7","mysql-8.0.36"]'
  matrix_slim: &matrix_slim
    php: '["8.1"]'
    mysql: '["mysql-5.7"]'

global:
  composer:
    dev_ref: &dev_ref dev-b-7.0.x

install:
  matrix: *matrix
  git:
    default_ref: 'b-7.0.x'
    enterprise_ref: 'b-7.0.x'
  composer:
    dev_ref: *dev_ref
    transform: |
      {
        "preferred-install": {
          "oxid-esales/*": "source",
          "oxid-professional-services/*": "source",
          "ddoe/*": "source"
        },
        "require": {
          "oxid-esales/twig-component": "dev-b-7.0.x",
          "oxid-esales/twig-admin-theme": "dev-b-7.0.x",
          "oxid-esales/apex-theme": "dev-b-7.0.x"
        }
      }

runscript:
  matrix: *matrix

runslim:
  matrix: *matrix_slim

sonarcloud:
  matrix: *matrix_slim

finish:
  matrix: *matrix
