workflow:
  matrix: &matrix
    php: &matrix_php '["8.0","8.1"]'
    mysql: &matrix_mysql '["5.7","8.0.36"]'
  matrix_slim: &matrix_slim
    php: &matrix_php '["8.1"]'
    mysql: &matrix_mysql '["5.7"]'

global:
  git: &git
    default_ref: &default_ref 'b-7.0.x'
    safe_ref_name: 'b-7.0.x'
    enterprise_ref: 'b-7.0.x'

  composer: &composer
    dev_ref: &dev_ref dev-b-7.0.x

install: &install
  matrix: *matrix
  git: *git
  composer:
    dev_ref: *dev_ref
    transform: |
      {
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source"
          },
          "require": {
              "oxid-esales/twig-component": "dev-b-7.0.x",
              "oxid-esales/twig-admin-theme": "dev-b-7.0.x",
              "oxid-esales/apex-theme": "dev-b-7.0.x"
          }
      }

# BEGIN Deprecated, will be superseded by install:
prepare_shop: *install

install_shop:
  matrix: *matrix
  git: *git

install_shop_with_modules: *install

install_module:
  matrix: *matrix
  git:
    module:
      ref: *default_ref
  composer: *composer
# END Deprecated

runscript:
  matrix: *matrix

runslim:
  matrix: *matrix_slim

phpunit:
  matrix: *matrix

codeception:
  matrix: *matrix
  composer: *composer
  suite: 'acceptance'

runtest:
  matrix: *matrix
  composer:
    transform: |
      {
          "require-dev": {
              "oxid-esales/tests-deprecated-ce": "dev-b-7.0.x",
              "codeception/module-webdriver": "^3.1",
              "phpunit/phpunit": "^9.1.1"
          }
      }

sonarcloud:
  matrix: *matrix_slim

phpcs_tests:
  matrix: *matrix_slim

phpmd:
  matrix: *matrix_slim

phpstan:
  matrix: *matrix_slim

styles:
  matrix: *matrix_slim
  composer: *composer

finish:
  matrix: *matrix
