workflow:
  matrix: &matrix
    # We only test the latest recommended versions here but both template engines
    php: &matrix_php '["8.0","8.1"]'
    mysql: &matrix_mysql '["5.7","8.0"]'

global:
  git: &git
    default_ref: &default_ref 'b-7.0.x'

  composer: &composer
    dev_ref: &dev_ref dev-b-7.0.x

prepare_shop:
  matrix: *matrix
  git: *git
  composer:
    dev_ref: *dev_ref
    transform: |
      {
          "require": {
              "oxid-esales/twig-component": "dev-b-7.0.x",
              "oxid-esales/twig-admin-theme": "dev-b-7.0.x",
              "oxid-esales/apex-theme": "dev-b-7.0.x"
          }
      }

install_shop:
  matrix: *matrix
  git: *git

install_module:
  matrix: *matrix
  git:
    module:
      ref: *default_ref
  composer: *composer

phpunit:
  matrix: *matrix

codeception:
  matrix: *matrix
  composer: *composer
  suite: 'acceptance'

runtest:
  matrix: *matrix
  composer:
    transform: |
      {
          "require-dev": {
              "oxid-esales/tests-deprecated-ce": "dev-b-7.0.x",
              "codeception/module-webdriver": "^3.1",
              "phpunit/phpunit": "^9.1.1"
          }
      }

sonarcloud:
  matrix: &matrix_slim
    php: '["8.0"]'
    mysql: '["5.7"]'

phpcs_tests:
  matrix: *matrix_slim

styles:
  matrix: *matrix_slim
  composer: *composer

finish:
  matrix: *matrix
