workflow:
  matrix: &matrix
    # We only test the latest recommended versions here but both template engines
    php: &matrix_php '["8.3","8.4"]'
    mysql: &matrix_mysql '["mysql-5.7","mysql-8.0.36","mariadb-11"]'
  matrix_slim: &matrix_slim
    php: '["8.4"]'
    mysql: '["mysql-8.0.36"]'
global:
  git: &git
    default_ref: &default_ref 'b-7.4.x'
    enterprise_ref: 'b-7.4.x'

  composer: &composer
    dev_ref: &dev_ref dev-b-7.4.x

install_shop_with_modules: &install
  matrix: *matrix
  git: *git
  composer:
    dev_ref: *dev_ref
    transform: |
      {
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source"
          },
          "require": {
              "oxid-esales/twig-component": "dev-b-7.4.x",
              "oxid-esales/twig-admin-theme": "dev-b-7.4.x",
              "oxid-esales/apex-theme": "dev-b-7.4.x"
          }
      }

# BEGIN Deprecated, will be superseded by install:
prepare_shop: *install

install_shop:
  matrix: *matrix
  git: *git

install_module:
  matrix: *matrix
  git:
    module:
      ref: *default_ref
  composer: *composer
# END Deprecated

runscript:
  matrix: *matrix

runslim:
  matrix: *matrix_slim

phpunit:
  matrix: *matrix

codeception:
  matrix: *matrix
  composer: *composer

runtest:
  matrix: *matrix
  composer:
    transform: |
      {
          "require-dev": {
              "oxid-esales/tests-deprecated-ce": "dev-b-7.4.x",
              "codeception/module-webdriver": "^3.1",
              "phpunit/phpunit": "^9.1.1"
          }
      }


sonarcloud:
  matrix: *matrix_slim

phpcs_tests:
  matrix: *matrix_slim

phpmd:
  matrix: *matrix_slim

phpstan:
  matrix: *matrix_slim

styles:
  matrix: *matrix_slim
  composer: *composer

finish:
  matrix: *matrix
