install:
  method: legacy
  cache:
    prepared_shop: false
  git:
    ref: '{{ .Data.install.git.safe_ref_name }}'
  composer:
    root_url: ''
    transform: ''
  skip_shop_installation: true

runscript: &runscript
  component:
    path: ''
  deprecated:
    path: ''
    composer:
      transform: |
        {
            "require-dev": {
                "oxid-esales/testing-library": "{{ .Data.global.composer.dev_ref }}",
                "oxid-esales/tests-deprecated-ce": "{{ .Data.global.composer.dev_ref }}",
                "codeception/module-webdriver": "^3.1",
                "phpunit/phpunit": "^9.1.1"
            }
        }

runslim:
  <<: *runscript

finish:
  slack_title: '{{ .Github.Repository }} ({{ .Github.Ref }}) by {{ .Github.Actor }}'
