# This config overrides defaults.yml to set the necessary settings for
# enterprise edition.
# You also need to make sure that the following secrets are defined:
# - CACHE_ENDPOINT
# - CACHE_ACCESS_KEY
# - CACHE_SECRET_KEY
# - enterprise_github_token

# See docs/actions/prepare_shop.md for more information.
install:
  git:
    ref: '{{ .Data.install.git.default_ref }}'
    enterprise_ref: '{{ .Github.RefName }}'
  composer:
    transform: |
      {
        "config": {
          "github-protocols": ["https"]
        },
        "preferred-install": {
          "oxid-esales/*": "source",
          "oxid-professional-services/*": "source",
          "ddoe/*": "source"
        },
        "require": {
          "oxid-esales/oxideshop-pe": "{{ .Data.install.composer.ref_name }}",
          "oxid-esales/oxideshop-ee": "{{ .Data.install.composer.ref_name }}",
          "oxid-esales/twig-component": "{{ .Data.install.composer.ref_name }}",
          "oxid-esales/twig-component-pe": "{{ .Data.install.composer.ref_name }}",
          "oxid-esales/twig-component-ee": "{{ .Data.install.composer.ref_name }}",
          "oxid-esales/twig-admin-theme": "{{ .Data.install.composer.ref_name }}",
          "oxid-esales/apex-theme": "{{ .Data.install.composer.ref_name }}"
        },
        "require-dev": {
          "oxid-esales/codeception-modules": "{{ .Data.install.composer.ref_name }}",
          "oxid-esales/codeception-page-objects": "{{ .Data.install.composer.ref_name }}"
        },
        "repositories": {
          "oxid-esales/twig-component-ee": {
            "type": "git",
            "url": "https://github.com/OXID-eSales/twig-component-ee.git"
          },
          "oxid-esales/twig-component-pe": {
            "type": "git",
            "url": "https://github.com/OXID-eSales/twig-component-pe.git"
          },
          "oxid-esales/oxideshop-ee": {
            "type": "git",
            "url": "https://github.com/OXID-eSales/oxideshop_ee.git"
          },
          "oxid-esales/oxideshop-pe": {
            "type": "git",
            "url": "https://github.com/OXID-eSales/oxideshop_pe.git"
          }
        }
      }
  cache:
    prepared_shop_prefix: 'preparedShop-ee-{{ .Github.SHA }}-{{ .Github.RunID }}'
    prefix: &install_shop_prefix 'shopInstallation-ee-{{ .Github.SHA }}-{{ .Github.RunID }}'

runscript:
  load_shop: *install_shop_prefix

runslim:
  load_shop: *install_shop_prefix

sonarcloud:
  matrix:
    testplan: 'skip'
