install:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source"
          },
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.install.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.install.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.install.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.install.composer.dev_ref }}",
              "{{ .Data.custom.org }}/{{ .Data.custom.name }}": "{{ .Data.install.composer.ref_name }}"
          },
          "repositories": {
            "{{ .Data.custom.org }}/{{ .Data.custom.name }}": {
              "type": "git",
              "url": "https://github.com/{{ .Github.Repository }}.git"
            }
          }
      }

  activate_modules: {{ .Data.custom.ids }}

runscript: &runscript
  module:
    path: 'vendor/{{ .Data.custom.org}}/{{ .Data.custom.name }}'

runslim:
  <<: *runscript

sonarcloud:
  strip_path: '/var/www/vendor/{{ .Data.custom.org}}/{{ .Data.custom.name }}/'
  parameters: |
    -Dsonar.language=php \
    -Dsonar.scm.provider=git \
    -Dsonar.sources=src \
    -Dsonar.tests=tests

finish:
  slack_title: '{{ print .Github.Repository }} ({{ .Data.install.git.ref }}) by {{ .Github.Actor }}'
