install_shop_with_modules:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source"
          },
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "{{ .Data.global.org }}/{{ .Data.global.name }}": "{{ .Data.global.composer.ref_name }}"
          },
          "repositories": {
            "{{ .Data.global.org }}/{{ .Data.global.name }}": {
              "type": "git",
              "url": "https://github.com/{{ .Data.global.repo }}.git"
            }
          }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:module:activate "{{ .Data.global.ids }}"
    {{ .Data.install_shop_with_modules.custom_script_container }}

runscript: &runscript
  matrix:
  module:
    path: 'vendor/{{ .Data.global.org}}/{{ .Data.global.name }}'

runslim:
  <<: *runscript

finish:
  slack_title: '{{ print .Data.global.name }} ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
