codeception:
  title: codeception_acceptance_{{ .Data.install_module.ids }}
  container:
    options: '-e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome -e XDEBUG_MODE=coverage -e THEME_ID=apex'
  configuration: '/var/www/vendor/{{ .Data.install_module.package_name }}/tests/codeception.yml'
  suite: 'acceptance'
  additional_options: '--coverage-xml=/var/www/coverage_codeception_acceptance_{{ .Data.install_module.ids }}.xml -g {{ .Data.install_module.ids }}'
  logfile:
    prefix: 'codeception'
  output:
    prefix: 'codeception-artifacts-{{ .Data.install_module.ids }}'
    files: |
      docker-compose.yml
      source/composer.json
      source/composer.lock
      source/source/config.inc.php
      source/source/log/oxideshop.log
      data/php/logs/error_log.txt
      source/tests/Codeception/_output
      source/dev-packages/{{ .Data.install_module.ids }}/tests/Codeception/_output
      source/vendor/{{ .Data.install_module.package_name }}/tests/Codeception/_output
      job_status*.txt
  coverage:
    path: 'source/coverage_codeception_acceptance_{{ .Data.install_module.ids }}.xml'
    prefix: coverage-reports-codeception_acceptance_{{ .Data.install_module.ids }}
