prepare_shop:
  matrix: &matrix
    php: '["8.1"]'
    mysql: '[ "mysql-5.7", "mysql-8.0", "mysql-8", "mysql-9", "mariadb-10", "mariadb-11" ]'

install_shop:
  matrix: *matrix
  max_parallel: 1

install_module:
  matrix: *matrix
  max_parallel: 1

install_shop_with_modules:
  matrix: *matrix
  max_parallel: 1

runscript:
  matrix: *matrix

runslim:
  matrix: *matrix

phpunit:
  matrix: *matrix

codeception:
  matrix: *matrix

runtest:
  matrix: *matrix

sonarcloud:
  matrix: *matrix
  max_parallel: 1

phpcs_tests:
  matrix: *matrix
  max_parallel: 1

phpmd:
  matrix: *matrix
  max_parallel: 1

phpstan:
  matrix: *matrix
  max_parallel: 1

styles:
  matrix: *matrix
  max_parallel: 1
