prepare_shop:
  matrix: &matrix
    php: '["8.2"]'
    mysql: '["8.0"]'

install_shop:
  matrix: *matrix
  max_parallel: 1

install_module:
  matrix: *matrix
  max_parallel: 1

phpunit:
  matrix: *matrix
  max_parallel: 1

codeception:
  matrix: *matrix
  max_parallel: 1

runtest:
  matrix: *matrix
  max_parallel: 1

sonarcloud:
  matrix: *matrix
  max_parallel: 1

phpcs_tests:
  matrix: *matrix
  max_parallel: 1

phpmd:
  matrix: *matrix
  max_parallel: 1

phpstan:
  matrix: *matrix
  max_parallel: 1

styles:
  matrix: *matrix
  max_parallel: 1
