# This overrides the default shop settings for scheduled workflows testing
# 7.0.x and 7.1.x because they can only be started from 8.0.x due
# to GitHub limitations on scheduled events

global:
  title: '{{ .Github.EventName }}-{{ .Data.install.git.default_ref }}'
  composer: &composer
    ref_name: 'dev-{{ .Data.install.git.default_ref }}'

init:
  cache:
    name: '{{ .Github.EventName }}-{{ .Data.install.git.default_ref }}-testplan-{{ .Env.GITHUB_REPOSITORY_ID }}-{{ .Github.SHA }}-{{ .Github.RunID }}'

install:
  git:
    ref: '{{ .Data.install.git.default_ref }}'
    enterprise_ref: '{{ .Data.install.git.default_ref }}'
    safe_ref_name: '{{ .Data.install.git.default_ref }}'
  composer: *composer

sonarcloud:
  target_branch: '{{ .Data.install.git.default_ref }}'

finish:
  slack_title: '{{ .Github.Workflow }} ({{ .Data.install.git.default_ref }}) on {{ .Github.Repository }} by {{ .Github.Actor }}'
