name: 'codeception_tests'
description: 'Executes codeception tests in a running shop'
inputs:
  php:
    type: string
    required: true
    description: 'Version of PHP for this instance'
  mysql:
    type: string
    required: true
    description: 'Version of MySQL for this instance'
  is_enterprise:
    type: boolean
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Add environment variables (ee)
      if: ${{ inputs.is_enterprise == 'true' }}
      shell: bash
      run: |
        cat >> $GITHUB_ENV <<EOF
        EXEC_PHP=docker-compose exec -T php
        TEST_YAML=vendor/oxid-esales/oxideshop-ee/Tests/codeception.yml
        PHPUNIT_LOGFILE=codeception_PHP${{ inputs.php }}_MYSQL${{ inputs.mysql }}_phpunit_log.txt
        CODECEPTION_OUTPUT_PATH=source/vendor/oxid-esales/oxideshop-ee/Tests/Codeception/_output
        EOF
        cat $GITHUB_ENV

    - name: Add environment variables (ce)
      if: ${{ inputs.is_enterprise == 'false' }}
      shell: bash
      run: |
        cat >> $GITHUB_ENV <<EOF
        EXEC_PHP=docker-compose exec -T php
        TEST_YAML=tests/codeception.yml
        PHPUNIT_LOGFILE=codeception_PHP${{ inputs.php }}_MYSQL${{ inputs.mysql }}_phpunit_log.txt
        CODECEPTION_OUTPUT_PATH=source/tests/Codeception/_output
        EOF
        cat $GITHUB_ENV

    - name: Build Codeception (ee)
      if: ${{ inputs.is_enterprise == 'true' }}
      shell: bash
      run: |
        $EXEC_PHP php vendor/bin/codecept build \
        -c vendor/oxid-esales/oxideshop-ee/Tests/codeception.yml

    - name: Run Codeception tests (ee)
      if: ${{ inputs.is_enterprise == 'true' }}
      shell: bash
      # why do we use run in ee and exec in ce?
      run: |
        docker-compose run -T \
          -e SELENIUM_SERVER_HOST=selenium \
          -e BROWSER_NAME=chrome \
          -e THEME_ID=apex php \
            php vendor/bin/codecept run acceptance,acceptanceAdmin \
          -c $TEST_YAML \
        --ext DotReporter \
        | tee $PHPUNIT_LOGFILE 2>&1 || true
        if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error|DID NOT FINISH' $PHPUNIT_LOGFILE; then exit 1; fi

    - name: Run Codeception tests (ce)
      if: ${{ inputs.is_enterprise == 'false' }}
      shell: bash
      run: |
        docker-compose exec -T \
          -e SELENIUM_SERVER_HOST=selenium \
          -e BROWSER_NAME=chrome \
          -e THEME_ID=apex \
          php vendor/bin/codecept run acceptance,acceptanceAdmin \
            -c $TEST_YAML \
            --ext DotReporter \
            --skip-group flow_theme \
            | tee $PHPUNIT_LOGFILE 2>&1 || true
        if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error|DID NOT FINISH' $PHPUNIT_LOGFILE; then
          exit 1
        fi

    - name: Upload PHPUnit Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-logs
        path: ${{ env.PHPUNIT_LOGFILE }}
        if-no-files-found: error
        retention-days: 7

    - name: Ensure that tests have been run
      shell: bash
      run: |
        if [ ! -s $PHPUNIT_LOGFILE ]; then
          echo "PHPUnit log file is empty! Seems like no tests have been run!"
          exit 1
        fi

    - name: Upload Codeception Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: codeception-artifacts-PHP${{ inputs.php }}-MYSQL${{ inputs.mysql }}
        path: ${{ env.CODECEPTION_OUTPUT_PATH }}/*
        if-no-files-found: ignore
        retention-days: 7