name: 'append_report'
description: 'Adds report and status snippets to the testplan artifact'
inputs:
  header:
    type: boolean
    required: false
    description: 'Do we need to write the phase header instead of a normal line'
    default: false
  priority:
    type: string
    required: false
    description: 'Priority helps with sorting phases and table content by becoming part of the file names in the artifact'
    default: '000'
  phase:
    type: string
    required: true
    description: 'Which phase are we in'
  job:
    type: string
    required: false
    description: 'Which job are we running'
    default: '-'
  title:
    type: string
    required: false
    description: 'Title of the job'
    default: 'default'
  php:
    type: string
    required: false
    description: 'PHP version for this matrix run'
    default: '0'
  mysql:
    type: string
    required: false
    description: 'MySQL version for this matrix run'
    default: '0'
  testplan:
    type: string
    required: false
    description: 'Testplan for this matrix run'
    default: 'none'
  status:
    type: string
    required: false
    description: 'Testplan for this matrix run'
    default: 'skipped'

runs:
  using: "composite"
  steps:
    - name: 'Write Phase header'
      if: ${{ inputs.header == 'true' }}
      shell: bash
      run: |
        mkdir -p reports job_status slack_reports
        cat <<EOF >reports/${{inputs.priority}}-${{ inputs.phase }}_header.md
        ## ${{ inputs.phase }} phase
        |Job |Title|PHP|MySQL|Testplan|Status|
        |:---|:----|--:|----:|:-------|:-----|
        EOF

    - name: 'Write summary'
      if: ${{ inputs.header == 'false' }}
      shell: bash
      # yamllint disable rule:line-length
      run: |
        REPORT_FILE='reports/${{inputs.priority}}-${{inputs.phase}}-${{inputs.job}}-${{inputs.title}}-PHP${{inputs.php}}_MYSQL${{inputs.mysql}}.md'
        STATUS_FILE='job_status/${{inputs.priority}}-${{inputs.phase}}-${{inputs.job}}-${{inputs.title}}-PHP${{inputs.php}}_MYSQL${{inputs.mysql}}.txt'
        SKIPPED_ICON='![Skipped](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-medium/26aa.png)'
        SUCCESS_ICON='![Success](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-medium/2705.png)'
        CANCELLED_ICON='![Cancelled](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-large/26ab.png)'
        FAILURE_ICON='![Failure](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-medium/274c.png)'
        JOB_STATUS='${{inputs.status}}'
        JOB_ICON="${JOB_STATUS^^}_ICON"
        if [[ '${{inputs.testplan}}' =~ ^http.* ]]; then
          BASE=$(echo '${{inputs.testplan}}'| sed -E 's|.+/(.*)$|\1|')
          TP="[${BASE}](${{inputs.testplan}})"
        else
          TP="${{inputs.testplan}}"
        fi
        mkdir -p reports job_status
        echo "|${{inputs.job}}|${{inputs.title}}|${{inputs.php}}|${{inputs.mysql}}|${TP}|${!JOB_ICON} ${JOB_STATUS}|" >"${REPORT_FILE}"
        echo "${JOB_STATUS}" >"${STATUS_FILE}"

    - name: Upload Artifacts
      # yamllint enable rule:line-length

      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: testplan
        path: |
          job_status/*.txt
          reports/*.md
          slack_reports/*.md
        if-no-files-found: ignore
        retention-days: 7
