name: 'append_report'
description: 'Appends data to the job_status'
inputs:
  header:
    type: boolean
    required: false
    description: 'do we need to write the phase header instead of a normal line'
    default: false
  priority:
    type: string
    required: false
    description: 'Priority helps with sorting phases and table content by becoming part of the file names in the artifact'
    default: '000'
  phase:
    type: string
    required: true
    description: 'Which phase are we in'
  job:
    type: string
    required: false
    description: 'Which job are we running'
    default: '-'
  title:
    type: string
    required: false
    description: 'Title of the job'
    default: 'default'
  php:
    type: string
    required: false
    description: 'PHP version for this matrix run'
    default: '0'
  mysql:
    type: string
    required: false
    description: 'MySQL version for this matrix run'
    default: '0'
  template_engine:
    type: string
    required: false
    description: 'Template engine for this matrix run'
    default: 'none'
  testplan:
    type: string
    required: false
    description: 'Testplan for this matrix run'
    default: 'none'
  status:
    type: string
    required: false
    description: 'Testplan for this matrix run'
    default: 'skipped'

runs:
  using: "composite"
  steps:
    - name: 'Write Phase header'
      if: ${{ inputs.header == 'true' }}
      shell: bash
      run: |
        cat <<EOF >report-${{inputs.priority}}-${{ inputs.phase }}_header.md
        ## ${{ inputs.phase }} phase
        |Job |Title|PHP|MySQL|Template engine|Testplan|Status|
        |:---|:----|--:|----:|--------------:|:-------|:-----|
        EOF

    - name: 'Write summary'
      if: ${{ inputs.header == 'false' }}
      shell: bash
      # yamllint disable rule:line-length
      run: |
        SKIPPED_ICON='![Skipped](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-medium/26aa.png)'
        SUCCESS_ICON='![Success](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-medium/2705.png)'
        CANCELLED_ICON='![Cancelled](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-large/26ab.png)'
        FAILURE_ICON='![Failure](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-medium/274c.png)'
        JOB_STATUS='${{inputs.status}}'
        JOB_ICON="${JOB_STATUS^^}_ICON"
        echo "ICON=${JOB_ICON} value='${!JOB_ICON}'"
        echo "|${{inputs.job}}|${{inputs.title}}|${{inputs.php}}|${{inputs.mysql}}|${{inputs.template_engine}}|[${{inputs.testplan}}]|${!JOB_ICON} ${JOB_STATUS}|" >"report-${{inputs.priority}}-${{inputs.phase}}_${{inputs.job}}-${{inputs.title}}-PHP${{inputs.php}}_MYSQL${{inputs.mysql}}_TE${{inputs.template_engine}}.md"
        echo "${JOB_STATUS}" >"job_status-${{inputs.priority}}-${{inputs.phase}}_${{inputs.job}}-${{inputs.title}}-PHP${{inputs.php}}_MYSQL${{inputs.mysql}}_TE${{inputs.template_engine}}.txt"

    - name: Upload Artifacts
      # yamllint enable rule:line-length

      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: job_status
        path: |
          job_status-*.txt
          report-*.md
        if-no-files-found: ignore
        retention-days: 7
