name: 'append_report'
description: 'Appends data to the job_status'
inputs:
  header:
    type: boolean
    required: false
    description: 'do we need to write the phase header instead of a normal line'
    default: false
  phase:
    type: string
    required: true
    description: 'Which phase are we in'
  job:
    type: string
    required: false
    description: 'Which job are we running'
    default: '-'
  title:
    type: string
    required: false
    description: 'Title of the job'
    default: '-'
  php:
    type: string
    required: false
    description: 'PHP version for this matrix run'
    default: '-'
  mysql:
    type: string
    required: false
    description: 'MySQL version for this matrix run'
    default: '-'
  template_engine:
    type: string
    required: false
    description: 'Template engine for this matrix run'
    default: '-'
  testplan:
    type: string
    required: false
    description: 'Testplan for this matrix run'
    default: '-'
  status:
    type: string
    required: false
    description: 'Testplan for this matrix run'
    default: 'skipped'

env:
  SKIPPED_ICON: '![Skipped](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-medium/26aa.png)'
  SUCCESS_ICON: '![Success](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-medium/2705.png)'
  CANCELLED_ICON: '![Cancelled](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-large/26ab.png)'
  FAILURE_ICON: '![Failure](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-medium/274c.png)'

runs:
  using: "composite"
  steps:
    - name: 'Write Phase header'
      if: ${{ inputs.header == 'true' }}
      shell: bash
      run: |
        cat <<EOF >report_${{ inputs.phase }}_000_header.md
        ## ${{ inputs.phase }} phase
        |Job |Title|PHP|MySQL|Template engine|Testplan|Status|
        |:---|:----|--:|----:|--------------:|:-------|:-----|
        EOF

    - name: 'Write summary'
      if: ${{ inputs.header == 'false' }}
      shell: bash
      # yamllint disable rule:line-length
      run: |
        JOB_STATUS='${{inputs.status}}'
        JOB_ICON="${JOB_STATUS^^}_ICON"
        echo "|${{inputs.job}}|${{inputs.title}}|${{inputs.php}}|${{inputs.mysql}}|${{inputs.template_engine}}|[${{inputs.testplan}}]|${!JOB_ICON} ${JOB_STATUS}|" >"report_${{inputs.phase}}_${{inputs.job}}_${{inputs.title}}.md"
        echo "${JOB_STATUS}" >"job_status-${{inputs.phase}}_${{inputs.job}}-${{sinputs.title}}-PHP${{inputs.php}}_MYSQL${{inputs.mysql}}_TE${{inputs.template_engine}}.txt"

    - name: Upload Artifacts
      # yamllint enable rule:line-length

      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: job_status
        path: |
          job_status-${{inputs.phase}}_${{inputs.job}}-${{sinputs.title}}-PHP${{inputs.php}}_MYSQL${{inputs.mysql}}_TE${{inputs.template_engine}}.txt
          report_${{inputs.phase}}*.md
        if-no-files-found: ignore
        retention-days: 7
