name: 'stop_shop'
description: 'Stops a running shop instance'
runs:
  using: "composite"
  steps:
    - name: Stop containers
      if: always()
      shell: bash
      run: |
        # stop_shop: Stop containers
        docker-compose down
