name: 'stop_shop'
description: 'Stops a running shop instance'
inputs:
  debug:
    type: boolean
    description: 'Enable debugging'
    default: false
    required: false

runs:
  using: "composite"
  steps:
    - name: Stop containers
      if: always()
      shell: bash
      run: |
        # stop_shop: Stop containers
        docker-compose down
