name: 'stop_shop'
description: 'Stops a running shop instance'
inputs:
  debug:
    type: string
    description: 'Appended to debugging scripts'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Output docker logs
      if: always()
      shell: bash
      run: |
        # stop_shop: Output docker logs if make up failed
        docker compose logs --tail=all >>docker-compose.log
        for c in $(docker ps -aq); do
          echo -e "\033[0;35m###  Logs for $c ###\033[0m"
          docker logs -n 2000 $c >docker-$c.log
        done

    - name: Stop containers
      if: always()
      shell: bash
      run: |
        # stop_shop: Stop containers
        ${{ inputs.debug }}
        docker compose down
