name: 'stop_shop'
description: 'Stops a running shop instance'
inputs:
  debug:
    type: string
    description: 'Appended to debugging scripts'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Stop containers
      if: always()
      shell: bash
      run: |
        # stop_shop: Stop containers
        docker compose down
        ${{ inputs.debug }}
