name: 'phpunit'
description: 'Executes phpunit tests in a running container and uploads the logs as artefacts'
inputs:
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  configuration:
    type: string
    required: false
    description: 'Name of the configuration file'
    default: 'phpunit.xml'
  test:
    type: string
    required: false
    description: 'Name of the test or folder to run'
    default: 'tests/Unit'
  additional_options:
    type: string
    required: false
    description: 'Optional: Additional options to pass to phpunit'
    default: ''
  logfile:
    type: string
    required: false
    description: 'Name of the output logfile'
    default: 'phpunit_log.txt'
  logfile_artifact:
    type: string
    required: false
    description: 'Github run artifact to put the logfile in'
    default: 'phpunit-logs'
  output_files:
    type: string
    required: false
    description: 'phpunit output and test settings'
    default: |
      source/unit.cov
      source/source/log/oxideshop.log
      data/php/logs/error_log.txt
  output_artifact:
    type: string
    required: false
    description: 'Github run artifact for the phpunit output'
    default: 'phpunit-artifacts'
  coverage_path:
    type: string
    required: false
    description: 'Path for the coverage file, not uploaded if it is empty'
    default: ''
  coverage_artifact:
    type: string
    required: false
    description: 'Github run artifact for the coverage file'
    default: 'coverage-reports'
  failure_pattern:
    type: string
    required: false
    description: 'Grep pattern which indicate that the test failed'
    default: 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error'
runs:
  using: "composite"
  steps:
    - name: Run PHPUnit tests
      shell: bash
      run: |
        # phpunit: Run PHPUnit tests
        touch "${{ inputs.logfile }}"
        docker-compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \
          ${{ inputs.container_name}} \
          php vendor/bin/phpunit \
            -c "${{ inputs.configuration }}" \
            ${{ inputs.additional_options }} \
            "${{ inputs.test }}" \
          | tee "${{ inputs.logfile }}" || true

    - name: Upload Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.logfile_artifact }}
        path: ${{ inputs.logfile }}
        if-no-files-found: error
        retention-days: 7

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.output_artifact }}
        path: |
          ${{ inputs.logfile }}
          ${{ inputs.output_files }}
          ${{ inputs.coverage_path }}
        if-no-files-found: ignore
        retention-days: 7

    - name: Upload Coverage Report
      if: ${{  always() && inputs.coverage_path != '' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.coverage_artifact }}
        path: ${{ inputs.coverage_path }}
        if-no-files-found: ignore
        retention-days: 7

    - name: Output php error log
      if: always()
      shell: bash
      run: |
        # phpunit: Output php error log
        if [ -s data/php/logs/error_log.txt ]; then
          echo -e "\033[0;35mPHP error log\033[0m"
          cat data/php/logs/error_log.txt
        fi

    - name: Check results
      shell: bash
      run: |
        # phpunit: Check results
        PURPLE=$(echo -e "\033[0;31m")
        NOCOLOR=$(echo -e "\033[0m")
        if [ ! -s "${{ inputs.logfile }}" ]; then
          cat <<EOF
        ${PURPLE}###############################################################################
        ### Log file is empty! Seems like no tests have been run!
        ###############################################################################${NOCOLOR}
        EOF
          exit 1
        fi
        cat >failure_pattern.tmp <<EOF
        ${{ inputs.failure_pattern}}
        EOF
        sed -e 's|(.*)\r|$1|' -i failure_pattern.tmp 
        while read -r LINE ; do
            if grep -q -E "${LINE}" "logfile.txt"; then
            echo -e "\033[0;31m phpunit test foobar failed matching pattern ${LINE}"
            grep -E "${LINE}" "logfile.txt"
            exit 1
        else
            echo -e "\033[0;32m phpunit test foobar passed matching pattern ${LINE}"
        fi
        done <failure_pattern.tmp        
        if [[ -n "${{ inputs.coverage_path }}" && ! -s "${{ inputs.coverage_path }}" ]]; then
          cat <<EOF
        ${PURPLE}###############################################################################
        ### "${{ inputs.coverage_path }}" is empty!
        ###############################################################################${NOCOLOR}
        EOF
          exit 1
        fi
