name: 'composer'
description: 'Generic composer wrapper'
inputs:
  action:
    type: string
    required: true
    description: 'Composer action to execute'
  parameters:
    type: string
    required: true
    description: 'List of parameters for the action'
  options:
    type: string
    required: false
    default: ''
    description: 'These options will be added at the end of every command'
  update:
    type: boolean
    required: false
    description: 'Run composer update after all the commands'
    default: false
  update_options:
    type: string
    required: false
    description: 'Options to pass along to composer when running composer update'
    default: '--no-interaction'
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'

runs:
  using: "composite"
  steps:
    - name: Run composer
      shell: bash
      run: |
        # composer: Run composer
        echo "${{ inputs.parameters }}%" | while IFS=$'\n' read -d '%' -r PARAMETER ; do
          echo -e "\033[0;35m### composer ${{ inputs.action }} ${PARAMETER} ${{inputs.options}} ###\033[0m"
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            composer ${{ inputs.action }} ${PARAMETER} ${{inputs.options}}
        done

        if [ '${{ inputs.update }}' == 'true' ]; then
          echo -e "\033[0;35m### Running composer update with ${{ inputs.update_options }}\033[0m"
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            composer update ${{ inputs.update_options }}
        fi
