name: 'styles'
description: 'Configures styles'
inputs:
  container:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  module_path:
    type: string
    required: false
    description: 'Path for the checkout and url'
    default: 'test-module'
  php:
    type: string
    required: true
    description: 'Version of PHP for this instance'
outputs:
  installed_shop_with_module:
    description: 'Name of the cached shop installation'
    value: ${{ steps.init.outputs.installed_shop_with_module }}
runs:
  using: "composite"
  steps:

      - name: Run phpstan
        id: phpstan
        if: always()
        run: |
          docker-compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \
            --workdir=/var/www/${{ inputs.module_path }} \
            ${{ inputs.container }} \
            bash -c "composer phpstan-report; composer phpstan"

      - name: Run phpmd
        id: phpmd
        if: always()
        continue-on-error: true
        run: |
          docker-compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \
            --workdir=/var/www/${{ inputs.module_path }} \
            ${{ inputs.container }} \
            bash -c "composer phpmd-report; composer phpmd"

      - name: Run phpcs
        if: always()
        run: |
          docker-compose ${{ inputs.container_method }} -T ${{ inputs.container_options }} \
            --workdir=/var/www/${{ inputs.module_path }} \
            ${{ inputs.container }} \
            php composer phpcs

      - name: Stop containers
        if: always()
        run: |
          make down
          sleep 2

      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: StylesLog-${{ inputs.php }}
          path: |
            source/${{ inputs.module_path }}/tests/reports/phpstan.report.json
            source/${{ inputs.module_path }}/tests/reports/phpmd.report.json
