name: 'styles'
description: 'Configures styles'
inputs:
  path:
    type: string
    required: false
    description: 'List of folders relative to the source folder to run the tests in'
    default: '.'
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  output_files:
    type: string
    required: false
    description: 'phpunit output and test settings'
    default: |
      source/tests/reports/phpstan*.report.json
      source/tests/reports/phpmd*.report.json
      source/tests/reports/phpcs*.report.json
  output_artifact:
    type: string
    required: false
    description: 'Github run artifact for the phpunit output'
    default: 'StylesLog'
runs:
  using: "composite"
  steps:
    - name: Run phpstan
      id: phpstan
      if: always()
      shell: bash
      run: |
        mkdir -p source/tests/reports
        PATHS=$(echo -n "${{ inputs.path }}"| tr '\n' ' ')
        for PATH in ${PATHS}; do
          echo -e "\033[0;35m###  Run phpstan in ${PATH} ###\033[0m"
          ID=${echo "${PATH}"|sed -e 's|/|_'}
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            bash -c "composer phpstan-report; composer phpstan --error-format=prettyJson '${PATH}' &>/var/www/tests/reports/phpstan-${ID}.report.json'"
        done

    - name: Run phpmd
      id: phpmd
      if: always()
      continue-on-error: true
      shell: bash
      run: |
        PATHS=$(echo -n "${{ inputs.path }}"| tr '\n' ' ')
        for PATH in ${PATHS}; do
          echo -e "\033[0;35m###  Run phpmd in ${PATH} ###\033[0m"
          ID=${echo "${PATH}"|sed -e 's|/|_'}
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            bash -c "composer phpmd-report; composer phpmd '${PATH}' --reportfile '/var/www/tests/reports/phpmd-${ID}.report.json'"
        done

    - name: Run phpcs
      if: always()
      shell: bash
      run: |
        PATHS=$(echo -n "${{ inputs.path }}"| tr '\n' ' ')
        for PATH in ${PATHS}; do
          echo -e "\033[0;35m###  Run phpcs in ${PATH} ###\033[0m"
          ID=${echo "${PATH}"|sed -e 's|/|_'}
          docker-compose ${{ inputs.container_method }} -T \
            ${{ inputs.container_options }} \
            ${{ inputs.container_name}} \
            composer phpcs --report=json --report-file="/var/www/tests/reports/phpcs-${ID}.report.json" "${PATH}"
        done

    - name: Stop containers
      if: always()
      shell: bash
      run: |
        make down

    - name: Upload log artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.output_artifact }}
        path: ${{ inputs.output_files }}
