name: 'styles'
description: 'Configures styles'
inputs:
  path:
    type: string
    required: true
    description: 'Folder to run the tests in'
  module_ids:
    type: string
    required: true
    description: 'Moduleids'
  install_options:
    type: string
    required: false
    description: 'Options to pass along to composer when running composer install'
    default: ''
  container_name:
    type: string
    required: false
    description: 'Name of the container to run the test in'
    default: 'php'
  container_options:
    type: string
    required: false
    description: 'Additional options to pass into the container'
    default: ''
  container_method:
    type: string
    required: false
    description: 'Method to execute the commands inside a container, either "run" or "exec"'
    default: 'exec'
  output_files:
    type: string
    required: false
    description: 'phpunit output and test settings'
    default: |
      source/tests/reports/phpstan*.report.json
      source/tests/reports/phpmd*.report.json
      source/tests/reports/phpcs*.report.json
      source/tests/reports/phpstan*.report.txt
      source/tests/reports/phpmd*.report.txt
      source/tests/reports/phpcs*.report.txt
      data/php/logs/error_log.txt
  output_artifact:
    type: string
    required: false
    description: 'Github run artifact for the styles output'
    default: 'StylesLog'
  debug:
    type: string
    description: 'Appended to debugging scripts'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Run composer install
      shell: bash
      run: |
        # styles: Run composer install
        ${{ inputs.debug }}
        mkdir -p source/tests/reports
        echo -e "\033[0;35m### Running composer install with ${{ inputs.install_options }}\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          --workdir '/var/www/dev-packages/${{ inputs.path }}' \
          ${{ inputs.container_name }} \
          composer install ${{ inputs.install_options }}

    - name: Run phpstan
      id: phpstan
      shell: bash
      run: |
        # styles: Run phpstan
        ${{ inputs.debug }}
        echo -e "\033[0;35m###  Run phpstan-report in ${{ inputs.path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          --workdir '/var/www/dev-packages/${{ inputs.path }}' \
          ${{ inputs.container_name }} \
          composer phpstan-report
        echo -e "\033[0;35m###  Run phpstan in ${{ inputs.path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          --workdir '/var/www/dev-packages/${{ inputs.path }}' \
          ${{ inputs.container_name }} \
          composer phpstan | tee -a source/tests/reports/phpstan-${{ inputs.module_ids }}.report.txt
        mv source/dev-packages/${{ inputs.path }}/phpstan.report.json source/tests/reports/phpstan-${{ inputs.module_ids }}.report.json

    - name: Run phpmd
      id: phpmd
      if: always()
      continue-on-error: true
      shell: bash
      run: |
        # styles: Run phpmd
        ${{ inputs.debug }}
        echo -e "\033[0;35m###  Run phpmd-report in ${{ inputs.path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          --workdir '/var/www/dev-packages/${{ inputs.path }}' \
          ${{ inputs.container_name }} \
          composer phpmd-report
        echo -e "\033[0;35m###  Run phpmd in ${{ inputs.path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          --workdir '/var/www/dev-packages/${{ inputs.path }}' \
          ${{ inputs.container_name }} \
          composer phpmd | tee -a source/tests/reports/phpmd-${{ inputs.module_ids }}.report.txt
        mv source/dev-packages/${{ inputs.path }}/phpmd.report.json source/tests/reports/phpmd-${{ inputs.module_ids }}.report.json

    - name: Run phpcs
      if: always()
      shell: bash
      run: |
        # styles: Run phpcs
        ${{ inputs.debug }}
        echo -e "\033[0;35m###  Run phpcs-report in ${{ inputs.path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          --workdir '/var/www/dev-packages/${{ inputs.path }}' \
          ${{ inputs.container_name }} \
          composer phpcs-report
        echo -e "\033[0;35m###  Run phpcs in ${{ inputs.path }} ###\033[0m"
        docker compose ${{ inputs.container_method }} -T \
          ${{ inputs.container_options }} \
          --workdir '/var/www/dev-packages/${{ inputs.path }}' \
          ${{ inputs.container_name }} \
          composer phpcs | tee -a source/tests/reports/phpcs-${{ inputs.module_ids }}.report.txt
        mv source/dev-packages/${{ inputs.path }}/phpcs.report.json source/tests/reports/phpcs-${{ inputs.module_ids }}.report.json

    - name: Output php error log
      if: always()
      shell: bash
      run: |
        # styles: Output php error log
        ${{ inputs.debug }}
        if [ -s data/php/logs/error_log.txt ]; then
          echo -e "\033[0;35mPHP error log\033[0m"
          cat data/php/logs/error_log.txt
        fi

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output_artifact }}
        path: ${{ inputs.output_files }}
