name: 'sonarcloud'
description: 'Runs sonarcloud in the given container'
inputs:
  coverage_artifact:
    type: string
    required: false
    description: 'Name of the artifact containing the coverage reports'
    default: 'coverage-reports'
  target_branch:
    type: string
    required: false
    description: 'Target branch for the scan'
    default: 'b-8.0.x'
  github_ref_name:
    type: string
    required: true
    description: 'Github reference for the scan'
  sonarcloud_organization:
    type: string
    required: false
    description: 'Name of the organization in sonarcloud'
    default: 'oxid-esales'
  sonarcloud_project_key:
    type: string
    required: false
    description: 'Project key in sonarcloud'
    default: 'OXID-eSales_oxideshop_ce'
  sonarcloud_project_name:
    type: string
    required: false
    description: 'Project name in sonarcloud'
    default: 'oxideshop_ce'
  sonarcloud_parameters:
    type: string
    required: false
    description: 'Parameters passed to the scanner'
    default: |
      -Dsonar.language=php
      -Dsonar.sources=source
      -Dsonar.tests=tests
      -Dsonar.cpd.php.minimumTokens=25
      -Dsonar.cpd.php.minimumLines=5
  sonar_token:
    type: string
    required: true
    description: 'Token for Sonarcloud'
  github_token:
    type: string
    required: true
    description: 'Token for Sonarcloud github access'
  output_files:
    type: string
    required: false
    description: 'sonarcloud output and test settings'
    default: |
      tests/*
  output_artifact:
    type: string
    required: false
    description: 'Github run artifact for the sonarcloud output'
    default: 'sonarcloud-artifacts'

runs:
  using: "composite"
  steps:
    - name: Download coverage artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.coverage_artifact }}
        path: ./source/coverage/

    - name: Fix Paths In Coverage Reports
      shell: bash
      run: |
          COVERAGE_FILES=""
          for FILE in $(find coverage-reports -iname '*_coverage.xml'); do
            echo -e "\033[0;35mFixing paths in ${FILE}\033[0m"
            sed -e 's#/var/www/##' -i ${FILE}
            COVERAGE_FILES="${COVERAGE_FILES},${FILE}"
          done
          # remove leading comma when adding this
          echo "COVERAGE_FILES=${COVERAGE_FILES:1}" | tee -a $GITHUB_ENV

    - name: Set target branch
      shell: bash
      run: |
        TARGET_BRANCH_PARAM="-Dsonar.branch.target=${{ inputs.target_branch }}"
        if [ "${{ github.ref_name}}" == "${{ github.event.repository.default_branch }}" ]; then
          TARGET_BRANCH_PARAM=""
        fi
        echo "TARGET_BRANCH_PARAM=$TARGET_PRANCH_PARAM" >> $GITHUB_ENV

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        args: >
          -Dsonar.organization=${{ inputs.sonarcloud_organization }}
          -Dsonar.projectKey=${{ inputs.sonarcloud_project_key }}
          -Dsonar.projectName=${{ inputs.sonarcloud_project_name }}
          -Dsonar.branch.name=${{ inputs.github_ref_name }}
          -Dsonar.php.coverage.reportPaths=${{ env.COVERAGE_FILES }}
          ${{ inputs.sonarcloud_parameters }}
          ${{ env.TARGET_BRANCH_PARAM }}
