name: 'slack_message'
description: 'Sends a status message to slack'
inputs:
  slack_webhook:
    type: string
    required: true
    description: 'URL for the channel web hook, see https://api.slack.com/apps/A04CAPK58G0/incoming-webhooks?'
  title:
    type: string
    required: true
    description: 'Title for the message, status will be added'
  summary_list:
    type: string
    required: false
    description: 'Multiple lines with Name and URL separated by a %'
    default: ''
  install_list:
    type: string
    required: false
    description: 'Name of the install job and its outcome or result separated by a %'
    default: ''
  test_list:
    type: string
    required: false
    description: 'Name of the job and its outcome or result separated by a %'
    default: ''
  report_list:
    type: string
    required: false
    description: 'Name of the job and its outcome or result separated by a %'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Prepare payload
      shell: bash
      run: prepare_payload.sh
      # Workaround for https://github.com/actions/runner/issues/665
      env:
        INPUT_SUMMARY_LIST: ${{ inputs.summary_list }}
        INPUT_INSTALL_LIST: ${{ inputs.install_list }}
        INPUT_TEST_LIST: ${{ inputs.test_list }}
        INPUT_REPORT_LIST: ${{ inputs.report_list }}
        INPUT_TITLE: ${{ inputs.title }}


    - name: Send custom JSON data to Slack workflow
      uses: slackapi/slack-github-action@v1
      with:
        payload-file-path: 'payload.yaml'
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
