name: dispatch-test_json
on:
  workflow_dispatch:
    inputs:
      testplan:
        type: string
        description: 'Location of the testplan'
        required: true
      runs_on:
        type: string
        description: 'Runner for this workflow'
        required: false
        default: '"ubuntu-latest"'

jobs:
  test:
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    steps:
      - name: 'Load variables'
        uses: zlatko-ms/varfiletoenv@v3
        with:
          paths: ./path/to/my/file.properties
      - name: 'Dump variables'
        run: |
          cat <<EOF
            workflow_matrix_php: $workflow_matrix_php
            workflow_matrix_mysql: $workflow_matrix_mysql
            workflow_runs_on: $workflow_runs_on

            test_string: $test_string
            test_wahr: $test_wahr
            test_falsch: $test_falsch
            test_number: $test_number
          EOF
