name: push-validate_workflows
# Validates workflow files on push
# yamllint disable-line rule:truthy
on: push

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    env:
      SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK_URL }}"
      # yamllint disable-line rule:line-length
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Lint yaml files
        id: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          format: 'github'
          config_data: |
            extends: default
            rules:
              document-start: disable
              line-length:
                max: 160
                level: warning
              new-line-at-end-of-file:
                level: warning
              trailing-spaces:
                level: warning

      - name: Run actionlint
        id: actionlint
        uses: raven-actions/actionlint@v1

      - name: actionlint Summary
        if: always()
        run: |
          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"

      - name: Send custom JSON data to Slack workflow
        if: ${{ env.SLACK_WEBHOOK != '' }}
        uses: slackapi/slack-github-action@v1
        with:
          # yamllint disable rule:line-length
          payload: >
            {
              "blocks": [
                { "type": "header",
                  "text":
                    { "type": "plain_text",
                      "emoji": true,
                      "text": "${{ github.workflow }} on ${{ github.repository }} by ${{ github.actor }} ${{ steps.checkout =='success' && steps.yamllint =='success' && steps.actionlint =='success' && 'Successful' || 'Failed' }}"
                    }
                },
                {
                "type": "divider"
                },
                { "type": "context",
                  "elements": [
                    { "type": "mrkdwn",
                      "text": "*Repository:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.repository }}/actions/runs/${{ github.run_id }}>\n"
                    }
                  ]
                },
                {
                "type": "divider"
                },
                { "type": "section",
                  "fields": [
                    { "type": "mrkdwn",
                      "text": "checkout: ${{ needs.checkout.result=='success' && ':white_check_mark:' || ':x:' }} ${{ needs.checkout.result }}"
                    },
                    { "type": "mrkdwn",
                      "text": "install_shop: ${{ needs.yamllint.result=='success' && ':white_check_mark:' || ':x:' }} ${{ needs.yamllint.result }}"
                    },
                    { "type": "mrkdwn",
                      "text": "unit_tests: ${{ needs.actionlint.result=='success' && ':white_check_mark:' || ':x:' }} ${{ needs.actionlint.result }}"
                    }
                  ]
                }
              ]
            }
          # yamllint enable rule:line-length
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
